tasks:
  - name: Setup
    init: pnpm install && pnpm turbo build gp sync-done setup
    env:
      NETLIFY_URL: http://localhost:8000
      DRUPAL_EXTERNAL_URL: http://localhost:8888
      DRUPAL_INTERNAL_URL: http://127.0.0.1:8888
      PUBLISHER_URL: http://localhost:8000
  - name: Storybook
    init: gp sync-await setup
    command: pnpm run --filter @custom/ui dev
  - name: Drupal
    init: gp sync-await setup
    command: pnpm run --filter @custom/cms dev
    env:
      NETLIFY_URL: http://localhost:8000
      DRUPAL_EXTERNAL_URL: http://localhost:8888
      DRUPAL_INTERNAL_URL: http://127.0.0.1:8888
      PUBLISHER_URL: http://localhost:8000
  - name: Gatsby
    init: gp sync-await setup
    command: pnpm run --filter @custom/website serve
    env:
      NETLIFY_URL: http://localhost:8000
      DRUPAL_EXTERNAL_URL: http://localhost:8888
      DRUPAL_INTERNAL_URL: http://127.0.0.1:8888
      PUBLISHER_URL: http://localhost:8000
  - name: Codegen
    init: gp sync-await setup
    command: pnpm --filter @custom/schema run watch
  - name: Decap Proxy
    init: gp sync-await setup
    command: pnpm run --filter @custom/decap start
  - name: Decap Dev
    init: gp sync-await setup
    command: pnpm run --filter @custom/decap dev

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - 'esbenp.prettier-vscode'
    - 'ZixuanChen.vitest-explorer'
    - 'GraphQL.vscode-graphql'
    - 'GraphQL.vscode-graphql-syntax'
    - 'eamodio.gitlens'
    - 'GitHub.vscode-pull-request-github'
    - 'GitHub.copilot'
    - 'dbaeumer.vscode-eslint'
    - 'ms-azuretools.vscode-docker'
    - 'ms-playwright.playwright'
    - 'denoland.vscode-deno'
    - 'bradlc.vscode-tailwindcss'
    - 'felixfbecker.php-debug'
    - 'humao.rest-client'
    - 'DEVSENSE.phptools-vscode'
    - 'GitHub.vscode-github-actions'
    - 'Graphite.gti-vscode'

ports:
  - port: 8000
    name: Gatsby
    onOpen: notify
  - port: 6006
    name: Storybook Dev
    onOpen: notify
  - port: 8888
    name: Drupal Dev
    onOpen: notify
  - port: 5173
    name: Decap Dev
    onOpen: notify
  - port: 8081
    name: Decap Proxy
    onOpen: notify
