# Schema for the configuration files of the silverback_ai_import module.
silverback_ai_import.settings:
  type: config_object
  label: 'silverback_ai_import settings'
  mapping:
    example:
      type: string
      label: 'Example'
