name: High Content Volume
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          server-token: 'local'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare
        run: pnpm turbo:prep
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: 'local'
          TURBO_TEAM: 'local'

      - name: 'Drupal: Start'
        run: pnpm --filter "@custom/cms" start &

      - name: 'Gatsby: Clean'
        run: pnpm --filter "@custom/website" clean

      - name: 'Drupal: Create content'
        run: pnpm --filter "@custom/cms" drush php:script scripts/create-lots-of-content/run.php

      - name: 'Gatsby: Full build'
        run: pnpm --filter "@custom/website" build:gatsby

      - name: 'Gatsby: Incremental build without new content'
        run: pnpm --filter "@custom/website" build:gatsby

      - name: 'Drupal: Create more content'
        run: pnpm --filter "@custom/cms" drush php:script scripts/create-lots-of-content/create-100-pages.php

      - name: 'Gatsby: Incremental build with new content'
        run: pnpm --filter "@custom/website" build:gatsby
