name: Test without Turbo cache
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Init check
        if: ${{ github.repository != 'AmazeeLabs/silverback-template'}}
        run:
          echo 'Please run the INIT script. See the root README.md for
          instructions.' && false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          server-token: 'local'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: pnpm turbo:test:force
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: 'local'
          TURBO_TEAM: 'local'

      - name: 'Logs: cms'
        run: cat /tmp/cms.log || true
        if: always()
      - name: 'Logs: website'
        run: cat /tmp/website.log || true
        if: always()
      - name: 'Logs: preview'
        run: cat /tmp/preview.log || true
        if: always()

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: tests/e2e/playwright-report/
          retention-days: 3
